In [3]:
# -----------------------------------------------------------------------------
# Authors:      Rafael Ballester-Ripoll <rballester@ifi.uzh.ch>
#
# Copyright:    ttrecipes project (c) 2017-2018
#               VMMLab - University of Zurich
#
# ttrecipes is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ttrecipes is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with ttrecipes.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

from __future__ import (absolute_import, division,
                        print_function, unicode_literals)
from future.builtins import range

from unittest import TestCase
import numpy as np
import teneva
import sampling

# import ttrecipes as tr


class TestSampling(TestCase):

    def test_random_sampling(self):

        N = 3
        I = 8
        P = 100

        # A joint PDF
        # Rs = [1, ] + [10, ]*(N-1) + [1, ]
        # pdf = tt.vector.from_list([np.random_sampling.rand(Rs[n], I, Rs[n+1]) for n in range(N)])
        # Rs = np.ones(N+1)
        # pdf = tt.vector.from_list([np.exp(-np.linspace(-7.5, 7.5, I)**2)[np.newaxis, :, np.newaxis]]*N)
        pdf = np.zeros((I,) * N)
        for i in range(I):
            pdf[i, :, i] = 1
#         pdf = tt.vector(pdf, eps=0)
        pdf = teneva.svd(pdf, e=0)
#         pdf = teneva.full(pdf)
        Xs = sampling.random_sampling(pdf, P)
        print(Xs)
        self.assertAlmostEqual(np.linalg.norm(Xs[:, 0] - Xs[:, 2]), 0)

In [4]:
TestSampling().test_random_sampling()

[[4. 0. 4.]
 [6. 5. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [1. 2. 1.]
 [5. 4. 5.]
 [4. 1. 4.]
 [6. 1. 6.]
 [0. 3. 0.]
 [1. 6. 1.]
 [6. 0. 6.]
 [1. 7. 1.]
 [0. 1. 0.]
 [0. 5. 0.]
 [5. 0. 5.]
 [2. 0. 2.]
 [6. 0. 6.]
 [6. 7. 6.]
 [0. 0. 0.]
 [4. 3. 4.]
 [0. 1. 0.]
 [3. 3. 3.]
 [3. 2. 3.]
 [5. 0. 5.]
 [2. 2. 2.]
 [1. 6. 1.]
 [7. 7. 7.]
 [5. 6. 5.]
 [2. 6. 2.]
 [6. 0. 6.]
 [6. 3. 6.]
 [2. 7. 2.]
 [0. 0. 0.]
 [6. 2. 6.]
 [4. 7. 4.]
 [3. 2. 3.]
 [4. 4. 4.]
 [7. 2. 7.]
 [0. 5. 0.]
 [3. 6. 3.]
 [1. 0. 1.]
 [4. 2. 4.]
 [5. 2. 5.]
 [3. 4. 3.]
 [3. 4. 3.]
 [4. 2. 4.]
 [6. 0. 6.]
 [3. 7. 3.]
 [2. 4. 2.]
 [4. 1. 4.]
 [5. 5. 5.]
 [7. 5. 7.]
 [7. 0. 7.]
 [2. 5. 2.]
 [2. 2. 2.]
 [6. 5. 6.]
 [3. 3. 3.]
 [6. 6. 6.]
 [6. 2. 6.]
 [5. 5. 5.]
 [0. 2. 0.]
 [0. 3. 0.]
 [4. 3. 4.]
 [1. 4. 1.]
 [2. 2. 2.]
 [7. 0. 7.]
 [2. 4. 2.]
 [2. 5. 2.]
 [2. 1. 2.]
 [2. 0. 2.]
 [3. 1. 3.]
 [5. 5. 5.]
 [6. 5. 6.]
 [0. 6. 0.]
 [2. 3. 2.]
 [2. 1. 2.]
 [3. 6. 3.]
 [6. 7. 6.]
 [0. 2. 0.]
 [0. 5. 0.]
 [5. 5. 5.]
 [7. 7. 7.]
 [2. 1. 2.]
 [2.